export const TODO_ACTION_TYPES = {
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    DONE_TODO: 'DONE_TODO',
    CHANGE_FILTER: 'CHANGE_FILTER',
    INIT_USER_TODOS: 'INIT_USER_TODOS'
}